version: "3.8"

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Map container port 8080 to host port 8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Example environment variable, adjust as needed
    volumes:
      - ./target:/app/target # Optional: Bind the target directory to allow updates
